version: "3.7"

services:
  mysql:
    container_name: mysql
    image: mysql:5.7
    command: [--lower_case_table_names=1]
    ports:
      - 3306:3306
    volumes:
      - volume-mysql:/var/lib/mysql
      - ./resources/build.sql:/docker-entrypoint-initdb.d/script.sql
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD

volumes:
  volume-mysql:

